# Generated by Django 4.2.6 on 2023-10-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://www.happyeater.com/images/default-food-image.jpg",
                max_length=500,
            ),
        ),
    ]
